name: endohiff
channels:
  - bioconda
dependencies:
  - python=3.11
  - einops=0.7.*
  - matplotlib=3.7.*
  - numpy=1.25.*
  - pillow=10.3.*
  - pip
  - polars=0.20.*
  - pyarrow=12.0.*
  - seaborn=0.13.*
  - tqdm=4.65
  - pip:
    - taichi==1.7.*
