"""Render a viability threshold map for a single environment.
"""

from argparse import ArgumentParser
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import numpy as np

from src.constants import MAX_HIFF
from src.graphics import VIABILITY_PALETTE, frameless_figure


def render_env_map(env_data):
    """Render a map of viability thresholds across an environment.
    """
    frameless_figure()
    plt.imshow(env_data.transpose(), VIABILITY_PALETTE)
    plt.clim(0, MAX_HIFF)


def save_env_map(env_data, file):
    """Render and save a map of viability thresholds across an environment.
    """
    render_env_map(env_data)
    plt.savefig(file, dpi=20)
    plt.close()


def main(input_file, output_file=None):
    if output_file is None:
        output_file = input_file.with_suffix('.png')
    else:
        output_file.parent.mkdir(exist_ok=True, parents=True)

    env_data = np.load(input_file)
    save_env_map(env_data, output_file)

    # Indicate the program completed successfully.
    return 0


if __name__ == '__main__':
    parser = ArgumentParser(
        description='Render a visualization of an environment.')
    parser.add_argument(
        'input_file', type=Path,
        help='An environment file (.npy) generated by this project')
    parser.add_argument(
        '--output_file', '-o', type=Path, default=None,
        help='Where to save the image (defaults to <input_file>.png)')
    args = vars(parser.parse_args())
    sys.exit(main(**args))
