from argparse import ArgumentParser
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import numpy as np

from ..constants import MAX_HIFF
from ..graphics import VIABILITY_PALETTE, frameless_figure


def render_env_map(env_data):
    """Render a map of minimum fitness values in an environment.
    """
    frameless_figure()
    plt.imshow(env_data.transpose(), VIABILITY_PALETTE)
    plt.clim(0, MAX_HIFF)


def save_env_map(env_data, filename):
    render_env_map(env_data)
    plt.savefig(filename, dpi=20)
    plt.close()


def main(input_filename, output_filename=None):
    if output_filename is None:
        output_filename = input_filename.with_suffix('.png')

    env_data = np.load(input_filename)
    save_env_map(env_data, output_filename)

    # Indicate the program completed successfully.
    return 0


if __name__ == '__main__':
    parser = ArgumentParser(
        description='Render a visualization of an environment.')
    parser.add_argument(
        'input_filename', type=Path,
        help='An environment file (.npy) generated by this project')
    parser.add_argument(
        '--output_filename', '-o', type=Path, default=None,
        help='Where to save the image (defaults to <input_filename>.png)')
    args = vars(parser.parse_args())
    sys.exit(main(**args))
